.\"
.\" ----------------------------------------------------------------------------
.\" "THE BEER-WARE LICENSE" (Revision 42):
.\" <mph@hoth.dk> wrote this file. As long as you retain this notice you
.\" can do whatever you want with this stuff. If we meet some day, and you think
.\" this stuff is worth it, you can buy me a beer in return Martin Topholm
.\" ----------------------------------------------------------------------------
.\"
.Dd August 25, 2012
.Dt XPING 8
.Os
.Sh NAME
.Nm xping
.Nd A terminal based, adhoc, multi target icmp-echo tool.
.Sh SYNOPSIS
.Nm
.Op Fl 46AVh
.Op Fl i Ar interval
.Op Ar host Op ...
.Sh DESCRIPTION
.Nm
is a simple PING program continiously probing multiple hosts using
ICMP-ECHO. As packets are received dots are printed on the screen.
Hosts not responding before next packet is due will get a questionmark
in the display. The probing stops when SIGINT is received.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl 4
Force xping to resolve IPv4 address only.
.It Fl 6
Force xping to resolve IPv6 address only.
.It Fl A
Print a bell character on stdout when a packet is missed.
.It Fl V
Print the "version" of xping and exit.
.It Fl a
Print a bell character on stdout on replies.
.It Fl h
Display program usage and exit.
.It Fl i Ar interval
Specifies interval between successive packets to a host. Default
is 1.0 seconds.
.El
.Sh DIAGNOSTICS
.Bl -tag -width indent
.It "socket: Operation not permitted"
.Nm
could not open a raw socket. Program should be setuid root or started
as root.
.El
.Sh AUTHORS
.Nm
was written by
.An Martin Topholm Aq mph@hoth.dk .
.Pp
.Nm
uses
.Nm libevent2
by An Niels Provos and Nick Mathewson,
.Nm uthash
by Troy D. Hanson, and
.Nm queue.h
from Regents of the University of California.
.Sh BUGS
.Nm
is not very informative on errors.
.Pp
Probably more.
